Add JpaRepository.getById for consistency, deprecated JpaRepository.g…
jcoreNL/spring-data-jpa pull request #2
Opened 2021-03-02 13:37 UTC by JesseW28

…etOne.

Also added two new tests where getById is used instead of getOne.

Closes #1697

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-03-02 13:55 UTC, SKrabbenborg requested changes
Please check if your actual first and last name are used in your git config. Currently you have JesseW28 as username in `git log`. 

`git config --get user.name` should return Jesse Wouters. Can be set by running `git config --global "Jesse Wouters"`

2021-03-02 13:55 UTC, SKrabbenborg commented on src/test/java/org/springframework/data/jpa/repository/AbstractPersistableIntegrationTests.java
> +	@Test // DATAJPA-1377
These should note the gh issue number. Apparently the DATAJPA are the old Jira identifiers

2021-03-02 13:55 UTC, SKrabbenborg commented on src/test/java/org/springframework/data/jpa/repository/UserRepositoryTests.java
> +	@Test // DATAJPA-1377
Ditto

2021-03-03 08:22 UTC, JesseW28 commented
@SKrabbenborg coming back on your comment: "Please check if your actual first and last name are used in your git config. Currently you have JesseW28 as username, see git log.

git config --get user.name should return Jesse Wouters. Can be set by running git config --global "Jesse Wouters"

The command git config --get user.name returns Jesse Wouters

2021-03-03 10:18 UTC, closed without merging